# Generated by Django 3.0.5 on 2020-05-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_orderkinde'),
        ('UserControl', '0004_auto_20200516_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='orderkind',
            field=models.ManyToManyField(to='cart.OrderKinde'),
        ),
    ]
