# Generated by Django 3.0.5 on 2020-05-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0005_access_orderkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='accsess_visitor',
            field=models.CharField(choices=[], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
