# Generated by Django 3.0.5 on 2020-05-23 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserControl', '0006_access_accsess_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='accsess_visitor',
        ),
        migrations.CreateModel(
            name='AccsessTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserControl.Access')),
                ('visitor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
