# Generated by Django 3.0.5 on 2020-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0007_auto_20200524_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='confirm_buy_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='confirm_sell_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='confirm_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='edit_buy_oder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='edit_sell_oder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='edit_shipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='make_buy_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='make_sell_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='make_shipment',
            field=models.BooleanField(default=False),
        ),
    ]
