# Generated by Django 3.0.5 on 2020-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0012_auto_20200530_1925'),
        ('UserControl', '0008_auto_20200524_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='bank_pose',
            field=models.ManyToManyField(to='accountside.BankPose'),
        ),
    ]
