# Generated by Django 3.0.5 on 2020-06-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0009_access_bank_pose'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='all_shipment_view',
            field=models.BooleanField(default=False),
        ),
    ]
