# Generated by Django 3.0.5 on 2020-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0010_access_all_shipment_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='accounting_after_return',
            field=models.BooleanField(default=False),
        ),
    ]
