# Generated by Django 3.0.5 on 2020-06-15 13:44

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0012_access_box'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='confirm_pay_order',
            field=models.BooleanField (default=False),
        ),
    ]
