# Generated by Django 3.0.5 on 2020-06-15 13:57

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0013_access_confirm_pay_order'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='make_pay_order',
            field=models.BooleanField (default=False),
        ),
    ]
