# Generated by Django 3.0.5 on 2020-06-22 07:04

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0014_access_make_pay_order'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='accounting_shipment',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='auto_inventory_maker',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='cancle_sending',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='confirm_settlment',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='deconfirm_buy_back',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='deconfirm_buy_order',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='defind_banck_pose',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='delete_buy_order',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='deliver_confirm_shipment',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='invoices_report',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='make_new_account',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='making_journal',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='product_views',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='products_detail',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='recieve_shipments',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='register',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='remove_sell_order',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='see_confirmed_buy',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='see_shipment_ready_for_accounting',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='sell_sended_order_report',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='send_for_SCM',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='send_shipments',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='settle_invoice',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='settled_shipment_reports',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_accountside',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_journals',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_shipment_orders',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='warhouse_confirm_buy_back',
            field=models.BooleanField (default=False),
        ),
    ]
