# Generated by Django 3.0.5 on 2020-06-22 07:24

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0015_auto_20200622_1134'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='make_buy_back',
            field=models.BooleanField (default=False),
        ),
    ]
