# Generated by Django 3.0.5 on 2020-06-22 08:24

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0016_access_make_buy_back'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='auto_journal',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='confirm_sell_back',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='make_sell_back',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_buy_orders',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_confirmed_buy',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_sell_back_orders',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_shipments_ready_for_accounting',
            field=models.BooleanField (default=False),
        ),
    ]
