# Generated by Django 3.0.5 on 2020-06-29 08:29

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0017_auto_20200622_1254'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='confirm_shipment_items_backed',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='view_shipment_items',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='view_shipment_items_backed',
            field=models.BooleanField (default=False),
        ),
    ]
