# Generated by Django 3.0.5 on 2020-06-29 14:16

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0018_auto_20200629_1259'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='settel_order',
            field=models.BooleanField (default=False),
        ),
        migrations.AddField (
            model_name='access',
            name='show_buy_back',
            field=models.BooleanField (default=False),
        ),
    ]
