# Generated by Django 3.0.5 on 2020-06-29 19:12

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('UserControl', '0019_auto_20200629_1846'),
    ]

    operations = [
        migrations.AddField (
            model_name='access',
            name='deliver_edit_orders',
            field=models.BooleanField (default=False),
        ),
    ]
