# Generated by Django 3.0.5 on 2020-06-30 15:19

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('cart', '0033_orderjournalrelation_descripion'),
        ('Shop', '0006_warehousedefinde_accountside'),
        ('accountside', '0017_safe_box'),
        ('UserControl', '0021_auto_20200630_1948'),
    ]

    operations = [
        migrations.AlterField (
            model_name='access',
            name='bank_pose',
            field=models.ManyToManyField (blank=True, null=True, to='accountside.BankPose'),
        ),
        migrations.AlterField (
            model_name='access',
            name='box',
            field=models.ManyToManyField (blank=True, null=True, to='accountside.Safe_Box'),
        ),
        migrations.AlterField (
            model_name='access',
            name='orderkind',
            field=models.ManyToManyField (blank=True, null=True, to='cart.OrderKinde'),
        ),
        migrations.AlterField (
            model_name='access',
            name='warehouse',
            field=models.ManyToManyField (blank=True, null=True, to='Shop.WareHouseDefinde'),
        ),
    ]
