# Generated by Django 3.0.5 on 2020-07-01 08:08

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('accountside', '0017_safe_box'),
        ('Shop', '0006_warehousedefinde_accountside'),
        ('cart', '0034_auto_20200701_1238'),
        ('UserControl', '0022_auto_20200630_1949'),
    ]

    operations = [
        migrations.AlterField (
            model_name='access',
            name='bank_pose',
            field=models.ManyToManyField (blank=True, to='accountside.BankPose'),
        ),
        migrations.AlterField (
            model_name='access',
            name='box',
            field=models.ManyToManyField (blank=True, to='accountside.Safe_Box'),
        ),
        migrations.AlterField (
            model_name='access',
            name='orderkind',
            field=models.ManyToManyField (blank=True, to='cart.OrderKinde'),
        ),
        migrations.AlterField (
            model_name='access',
            name='warehouse',
            field=models.ManyToManyField (blank=True, to='Shop.WareHouseDefinde'),
        ),
    ]
