# Generated by Django 3.0.5 on 2020-05-11 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComeForDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_date', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 22, 15, 7, 330369))),
                ('user_modifier', models.CharField(max_length=35)),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Order')),
            ],
            options={
                'verbose_name': 'Delivery Management',
                'ordering': ('id',),
            },
        ),
    ]
