# Generated by Django 3.0.5 on 2020-05-11 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0002_auto_20200511_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 0, 33, 54, 326569)),
        ),
    ]
