# Generated by Django 3.0.5 on 2020-05-11 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0003_auto_20200512_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 1, 15, 14, 565181)),
        ),
    ]
