# Generated by Django 3.0.5 on 2020-05-13 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0006_auto_20200513_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 19, 56, 46, 557608)),
        ),
    ]
