# Generated by Django 3.0.5 on 2020-05-14 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0007_auto_20200513_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 12, 50, 15, 54046)),
        ),
    ]
