# Generated by Django 3.0.5 on 2020-05-14 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0008_auto_20200514_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 13, 54, 32, 410358)),
        ),
    ]
