# Generated by Django 3.0.5 on 2020-05-14 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0009_auto_20200514_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 16, 19, 21, 552768)),
        ),
    ]
