# Generated by Django 3.0.5 on 2020-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCM', '0010_auto_20200514_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comefordelivery',
            name='coming_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
