# Generated by Django 3.0.5 on 2020-07-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('Shop', '0006_warehousedefinde_accountside'),
        ('cart', '0035_auto_20200701_1249'),
        ('SCM', '0011_auto_20200514_1622'),
    ]

    operations = [
        migrations.CreateModel (
            name='WarehouseInvoiceNumber',
            fields=[
                ('id', models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField ( )),
                ('order', models.ForeignKey (blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='cart.Order')),
                ('shipment', models.ForeignKey (blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='cart.Shipment')),
                ('warehouse', models.ForeignKey (blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='Shop.WareHouseDefinde')),
            ],
        ),
        migrations.CreateModel (
            name='WarehouseInvoiceItems',
            fields=[
                ('id', models.AutoField (auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_quantity', models.PositiveIntegerField ( )),
                ('output_quantity', models.PositiveIntegerField ( )),
                ('invoice_number',
                 models.ForeignKey (on_delete=django.db.models.deletion.CASCADE, to='SCM.WarehouseInvoiceNumber')),
                ('product', models.ForeignKey (on_delete=django.db.models.deletion.CASCADE, to='Shop.Product')),
            ],
        ),
    ]
