# Generated by Django 3.0.5 on 2020-07-01 16:22

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('SCM', '0012_warehouseinvoiceitems_warehouseinvoicenumber'),
    ]

    operations = [
        migrations.AddField (
            model_name='warehouseinvoicenumber',
            name='date',
            field=models.DateTimeField (blank=True, null=True),
        ),
    ]
