# Generated by Django 3.0.5 on 2020-07-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('cart', '0035_auto_20200701_1249'),
        ('SCM', '0013_warehouseinvoicenumber_date'),
    ]

    operations = [
        migrations.AlterField (
            model_name='warehouseinvoiceitems',
            name='input_quantity',
            field=models.PositiveIntegerField (default=0),
        ),
        migrations.AlterField (
            model_name='warehouseinvoiceitems',
            name='output_quantity',
            field=models.PositiveIntegerField (default=0),
        ),
        migrations.AlterField (
            model_name='warehouseinvoicenumber',
            name='order',
            field=models.OneToOneField (blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='cart.Order'),
        ),
        migrations.AlterField (
            model_name='warehouseinvoicenumber',
            name='shipment',
            field=models.OneToOneField (blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to='cart.Shipment'),
        ),
    ]
