# Generated by Django 3.0.5 on 2020-05-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local_id_def',
            options={'ordering': ('city', 'local_code')},
        ),
    ]
