# Generated by Django 3.0.5 on 2020-05-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountside', '0002_auto_20200512_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DifinitAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.AccountGroup')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('creditor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('description', models.TextField()),
                ('detailed_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.accountside')),
                ('difinit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.DifinitAccounts')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.DocumentNumber')),
            ],
        ),
        migrations.AddField(
            model_name='difinitaccounts',
            name='total_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.TotalAccounts'),
        ),
    ]
