# Generated by Django 3.0.5 on 2020-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0004_auto_20200514_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='difinitaccounts',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='totalaccounts',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
