# Generated by Django 3.0.5 on 2020-05-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0005_auto_20200516_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoJoournalFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_code', models.PositiveIntegerField()),
                ('debt_code', models.PositiveIntegerField()),
            ],
        ),
    ]
