# Generated by Django 3.0.5 on 2020-05-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0007_autojoournalfields_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumber',
            name='code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
