# Generated by Django 3.0.5 on 2020-05-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0010_bankcheck_bankpose_settel_kinde'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpose',
            name='accountside',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountside.accountside'),
            preserve_default=False,
        ),
    ]
