# Generated by Django 3.0.5 on 2020-05-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0011_bankpose_accountside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountside',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='area',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='credit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='id_code',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='property',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accountside',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accountside.local_id_def'),
        ),
    ]
