# Generated by Django 3.0.5 on 2020-05-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0012_auto_20200530_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcheck',
            name='branch',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
