# Generated by Django 3.0.5 on 2020-06-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0013_auto_20200530_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='autojoournalfields',
            name='credit_code_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autojoournalfields',
            name='credit_code_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autojoournalfields',
            name='debt_code_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autojoournalfields',
            name='debt_code_3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
