# Generated by Django 3.0.5 on 2020-06-05 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0014_auto_20200604_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='detailed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountside.accountside'),
        ),
    ]
