# Generated by Django 3.0.5 on 2020-06-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0015_auto_20200605_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.accountside')),
            ],
        ),
    ]
