# Generated by Django 3.0.5 on 2020-05-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_inventory_warehousedefinde'),
        ('raisingstock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder_items',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.WareHouseDefinde'),
        ),
    ]
