# Generated by Django 3.0.5 on 2020-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raisingstock', '0003_buyorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorder',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
