# Generated by Django 3.0.5 on 2020-05-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200515_2253'),
        ('accountside', '0007_autojoournalfields_name'),
        ('raisingstock', '0004_buyorder_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('checked_out_2', models.BooleanField(default=False, verbose_name='checked out')),
                ('user_craeter', models.CharField(max_length=45)),
                ('accountside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.accountside')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='buyorder',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='buyBackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raisingstock.buyBack')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.Product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
