# Generated by Django 3.0.5 on 2020-05-17 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raisingstock', '0006_warehouseinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raisingstock.wareHouseInvoice')),
            ],
        ),
    ]
