# Generated by Django 3.0.5 on 2020-05-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product_Sale_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=5)),
                ('slug', models.CharField(default='', max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductEchantion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('ech_quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('steps', models.PositiveIntegerField(null=True)),
                ('minQ_1', models.PositiveIntegerField(null=True)),
                ('maxQ_1', models.PositiveIntegerField(null=True)),
                ('off_persentage_1', models.PositiveIntegerField(null=True)),
                ('minQ_2', models.PositiveIntegerField(null=True)),
                ('maxQ_2', models.PositiveIntegerField(null=True)),
                ('off_persentage_2', models.PositiveIntegerField(null=True)),
                ('minQ_3', models.PositiveIntegerField(null=True)),
                ('maxQ_3', models.PositiveIntegerField(null=True)),
                ('off_persentage_3', models.PositiveIntegerField(null=True)),
                ('minQ_4', models.PositiveIntegerField(null=True)),
                ('maxQ_4', models.PositiveIntegerField(null=True)),
                ('off_persentage_4', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.FirstCategory')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, error_messages={TypeError: 'image did not saved'}, upload_to='')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(db_index=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sell_stock', models.PositiveIntegerField(db_index=True)),
                ('vat', models.PositiveIntegerField(default=0)),
                ('box', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Products', to='Shop.SubCategory')),
                ('echantion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.ProductEchantion')),
                ('off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.ProductOff')),
                ('salestate', models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.Product_Sale_State')),
            ],
            options={
                'ordering': ['price'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
