# Generated by Django 3.0.5 on 2020-05-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_inventory_warehousedefinde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='sell_stock',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='sell_quantity',
            new_name='stock',
        ),
    ]
