# Generated by Django 3.0.5 on 2020-06-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0017_safe_box'),
        ('Shop', '0005_auto_20200515_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousedefinde',
            name='accountside',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accountside.accountside'),
            preserve_default=False,
        ),
    ]
