# Generated by Django 3.0.5 on 2020-05-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='off',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
