# Generated by Django 3.0.5 on 2020-05-15 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200515_2253'),
        ('cart', '0004_auto_20200512_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warhouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Shop.WareHouseDefinde'),
            preserve_default=False,
        ),
    ]
