# Generated by Django 3.0.5 on 2020-05-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_warhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.Shipment'),
        ),
    ]
