# Generated by Django 3.0.5 on 2020-05-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200518_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderKinde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
