# Generated by Django 3.0.5 on 2020-05-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderkinde'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderkinde',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.OrderKinde'),
            preserve_default=False,
        ),
    ]
