# Generated by Django 3.0.5 on 2020-05-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20200518_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fianl_code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
