# Generated by Django 3.0.5 on 2020-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200518_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fianl_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
