# Generated by Django 3.0.5 on 2020-05-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_shipment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='checked_out_3',
            field=models.BooleanField(default=False, verbose_name='accounting'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='recieved'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='checked_out_2',
            field=models.BooleanField(default=False, verbose_name='send'),
        ),
    ]
