# Generated by Django 3.0.5 on 2020-05-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200515_2253'),
        ('cart', '0013_auto_20200522_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.WareHouseDefinde'),
            preserve_default=False,
        ),
    ]
