# Generated by Django 3.0.5 on 2020-05-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_shipment_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
