# Generated by Django 3.0.5 on 2020-05-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='cart.settlement'),
        ),
    ]
