# Generated by Django 3.0.5 on 2020-05-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
