# Generated by Django 3.0.5 on 2020-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_auto_20200524_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checked_out_3',
            field=models.BooleanField(default=False, verbose_name='checked out'),
        ),
        migrations.AddField(
            model_name='order',
            name='checked_out_4',
            field=models.BooleanField(default=False, verbose_name='checked out'),
        ),
    ]
