# Generated by Django 3.0.5 on 2020-05-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20200526_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
