# Generated by Django 3.0.5 on 2020-05-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0005_auto_20200515_2253'),
        ('cart', '0020_order_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipmentBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='recieved')),
                ('checked_out_2', models.BooleanField(default=False, verbose_name='send')),
                ('checked_out_3', models.BooleanField(default=False, verbose_name='accounting')),
                ('user_craeter', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('distributeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Shipment')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.WareHouseDefinde')),
            ],
        ),
    ]
