# Generated by Django 3.0.5 on 2020-05-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_shipmentback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shipmentBack'),
        ),
    ]
