# Generated by Django 3.0.5 on 2020-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_order_shipment_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='checked_out_4',
            field=models.BooleanField(default=False, verbose_name='disributer confirm'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='checked_out_5',
            field=models.BooleanField(default=False, verbose_name='accounting'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='checked_out_3',
            field=models.BooleanField(default=False, verbose_name='warehouse confirm'),
        ),
    ]
