# Generated by Django 3.0.5 on 2020-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20200526_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='checked_out_3',
            field=models.BooleanField(default=False, verbose_name='disributer confirm'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='checked_out_4',
            field=models.BooleanField(default=False, verbose_name='warehouse confirm'),
        ),
    ]
