# Generated by Django 3.0.5 on 2020-05-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0010_bankcheck_bankpose_settel_kinde'),
        ('cart', '0024_auto_20200527_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_settlment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_date', models.DateTimeField(auto_now_add=True)),
                ('usance_date', models.DateTimeField(blank=True, null=True)),
                ('serial_num', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('check_out_1', models.BooleanField(default=False)),
                ('check_out_2', models.BooleanField(default=False)),
                ('check_out_3', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountside.BankCheck')),
                ('bank_pose', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accountside.BankPose')),
                ('sell_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('settel_kinde', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountside.settel_kinde')),
            ],
        ),
    ]
