# Generated by Django 3.0.5 on 2020-05-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_delivery_settlment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_settlment',
            name='settel_kinde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.settlement'),
        ),
    ]
