# Generated by Django 3.0.5 on 2020-05-31 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0013_auto_20200530_2148'),
        ('cart', '0027_auto_20200531_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_settlment',
            name='bank_pose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountside.BankPose'),
        ),
        migrations.AlterField(
            model_name='delivery_settlment',
            name='serial_num',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
