# Generated by Django 3.0.5 on 2020-06-02 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200515_2253'),
        ('cart', '0028_auto_20200531_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=18)),
                ('off', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='sell price')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.Product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
