# Generated by Django 3.0.5 on 2020-06-05 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountside', '0014_auto_20200604_0126'),
        ('cart', '0029_orderitembackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderJournalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountside.DocumentNumber')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
            ],
        ),
    ]
