# Generated by Django 3.0.5 on 2020-06-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_orderjournalrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_convert_invoice',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
