# Generated by Django 3.0.5 on 2020-06-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_delivery_settlment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderjournalrelation',
            name='descripion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
