# Generated by Django 3.0.5 on 2020-07-01 08:08

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('cart', '0033_orderjournalrelation_descripion'),
    ]

    operations = [
        migrations.AddField (
            model_name='order',
            name='confirm_delete_date',
            field=models.DateTimeField (blank=True, null=True),
        ),
        migrations.AddField (
            model_name='order',
            name='modifier_remover_user',
            field=models.DateTimeField (blank=True, null=True),
        ),
        migrations.AddField (
            model_name='shipment',
            name='sended_date',
            field=models.DateTimeField (blank=True, null=True),
        ),
    ]
