# Generated by Django 3.0.5 on 2020-07-01 08:19

from django.db import migrations, models


class Migration (migrations.Migration):
    dependencies = [
        ('cart', '0034_auto_20200701_1238'),
    ]

    operations = [
        migrations.AlterField (
            model_name='order',
            name='modifier_remover_user',
            field=models.CharField (blank=True, max_length=40, null=True),
        ),
    ]
